### ISSUE TITLE
doesn't work when quotes are not present

### ISSUE THREAD

**Issue by cmpscabral** [alvesjtiago/hover-preview#1]
Filename needs quotes (single or double) for the plugin to work. Background images in css files use neither.

great work :) thanks!

**Comment by alvesjtiago** [comment]
Thanks! 😊
Working on it, I'll let you know when it's fixed.

**Comment by alvesjtiago** [comment]
@cmpscabral I've now added support for finding files inside parentheses as well. Let me know if this solves background images issues in css files.

**Comment by cmpscabral** [comment]
working :) tks
