### ISSUE TITLE
[Feature request] svg support

### ISSUE THREAD

**Issue by Kristinita** [alvesjtiago/hover-preview#11]
### 1. Request

It would be nice, if `svg` images will be support like [**other formats**](https://github.com/alvesjtiago/hover-preview/blob/master/hover_preview.py#L10).

### 2. Justification

SVG — [**one of most popularity**](https://w3techs.com/technologies/details/im-svg/all/all) image formats. I think, is a bad practice — ignore it.

### 3. Desirable behavior

User hover mouse to relative or absolute `svg` link → preview for full image show for user like other formats.

Thanks.

**Comment by alvesjtiago** [comment]
@Kristinita it definitely makes sense. Unfortunately rendering SVG as base64 inside an img src tag does not seam to be working inside ST3:

<img width="315" alt="screen shot 2017-02-15 at 13 28 40" src="https://cloud.githubusercontent.com/assets/407470/22974490/dab148ea-f382-11e6-9921-d510f75c8e6d.png">

Another issue at ST3 core should be submitted.

**Comment by r-stein** [comment]
I doubt this will be supported by Sublime Text soon.
If you are motivated enough you can use ImageMagick or an other program to convert svg and other images to preview thumbnail png-images. We do something similar at LaTeXTools (where pdf is a standard image format) [here](https://github.com/SublimeText/LaTeXTools/blob/v3.12.15/st_preview/preview_image.py#L86). However I don't think it is worth the effort for this.

**Comment by haizdesign** [comment]
Thanks for developing this! Can you add image dimensions below the actual image please?

**Comment by alvesjtiago** [comment]
@haizdesign of course. Can you please create a new issue with this request? Thank you

**Comment by haizdesign** [comment]
Done.

**Comment by AmjadHD** [comment]
#26
