### ISSUE TITLE
[Bug] Small square on hover to non-image link

### ISSUE THREAD

**Issue by Kristinita** [alvesjtiago/hover-preview#12]
### 1. Summary

If I hover mouse to non-image link, I see small square.

### 2. Expected behavior

Not small square.

### 3. Actual behavior

![Small square](http://i.imgur.com/Y2ETOYE.png)

### 4. Steps to reproduce

I'm not reproduce the problem in a version of Sublime Text without plugins and user settings.

I have a text in `test.md` file:

    [Kristina is my Love](http://kristinita.ru)

I hover my mouse to `http://kristinita.ru` → I get actual behavior.

If I disable HoverPreview, I'm not reproduce the problem.

### 5. Steps to debugging

1. I change my color scheme.
2. I [**clear Sublime Text Cache**](https://www.sublimetext.com/docs/3/revert.html).
3. I [**disable all packages**](http://stackoverflow.com/a/30857054/5951529) besides HoverPreview.
4. I temporarily remove all files into `Package/User`, `Data/Local` and `Data/Settings` folders.

No effect. Possibly, you know the reason of actual behavior?

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126

Thanks.

**Comment by alvesjtiago** [comment]
I'm sorry @Kristinita but I can't reproduce that bug neither on Windows 10 or Mac OS. Do you have any other text on the test.md file?

**Comment by Kristinita** [comment]
@alvesjtiago , 

> Do you have any other text on the test.md file?

No, only this text. 

But I repoduce the problem fo any link in any file format.

> I can't reproduce that bug neither on Windows 10 or Mac OS.

I can not too (see section 5), I don't understand, where the reason may be 😿 .

Thanks.

**Comment by alvesjtiago** [comment]
@Kristinita maybe the problem is with another plugin or user settings? Since it only happens when you have them enabled, maybe that's the issue. Can you try enabling one at a time and check which one can be causing that? Thanks

**Comment by Kristinita** [comment]
@alvesjtiago ,

> maybe the problem is with another plugin or user settings? Since it only happens when you have them enabled, maybe that's the issue.

I disable all packages besides HoverPreview, but the problem reproduce for me, see 5.3( .

I'll try in details to find the cause of the error, when I have more free time.

Thanks.

**Comment by alvesjtiago** [comment]
@Kristinita so if you open Sublime Text, create a single file and only have that file open on the sidebar called test.md, with the text ```[Kristina is my Love](http://kristinita.ru)``` and hover on ```http://kristinita.ru``` you get that square?

**Comment by Kristinita** [comment]
@alvesjtiago, I can fix the problem, most probable it no Hover Image Preview problem. But I'm don't glad Sublime Text behavior.

### 1. Steps to reproduce

I install PackageResourceViewer → `PackageResourceViewer: Open Resource` → `Hover Preview` → `hover_preview.py` → I edit and save file. My `hover_preview.py` file — **<https://www.pastery.net/ynvukq/>**.

I upgrade HoverPreview use Package Control → now I have last 0.0.8 version.

![0.0.8](http://i.imgur.com/g9bKOeX.png)

0.0.8 version `hover_preview.py` file — **<https://www.pastery.net/gexwug/>**. I see `Data/Installed Packages/Hover Image Preview.sublime-package` file → I have all correct files of current version.

I see in `Data/Packages/Hover Image Preview` folder and see in it folder my incorrect `hover_preview.py` file. I delete this file → I delete and reinstall Hover Image Preview → I don't reproduce the problem, I get expected behavior.

Thanks.
