### ISSUE TITLE
[BUG] Hover Preview Not Working When I Open Two Or More Project Folder

### ISSUE THREAD

**Issue by DingChil** [alvesjtiago/hover-preview#13]
## 1.Summary

My Hover Preview worked well in Sublime Text 3 when I just opened one project folder in the sidebar. But after I opened two or more project folders, Hover Preview did not show the image except that project in the last opened parent folder.

## 2.Expected behavior

Hover Preview worked normally when I opened more than two project folders.

## 3.Actual behavior

Hover Preview did not previewed the image when I hovered except that project in the last opened parent folder.

## 4.Steps to reproduce

Installing Hover Preview by Package Control and opening more than two project folders in Sublime Text 3.

## 5.Environment

Operating system:
Windows 10 home 14393.321 64-bit
Sublime Text:
Build 3126

Thanks

**Comment by alvesjtiago** [comment]
Thank you for reporting the issue @DingChil. I've just pushed version 0.0.9 which addresses the problem. Let me know if it's now working for you.

**Comment by DingChil** [comment]
@alvesjtiago Yes, the problem is sloved. Thanks for your work.
