### ISSUE TITLE
Preview fails with certain file names

### ISSUE THREAD

**Issue by jrappen** [alvesjtiago/hover-preview#14]
Preview fails when file name (excluding the extension) contains a dot:

```markdown
<!-- doesn't work -->

![description](subfolder/what.ever.jpg)
```

```markdown
<!-- works fine -->
![description](subfolder/whatever.jpg)
```

**Comment by alvesjtiago** [comment]
Thank you for reporting the issue @jrappen.
I've just released a new version (0.0.10) that should upload automatically on your end and fix the issue. Please let me know if it works now.
