### ISSUE TITLE
Feature Request - Image Sizes

### ISSUE THREAD

**Issue by haizdesign** [alvesjtiago/hover-preview#17]
Thanks for developing this! Can you add image dimensions below the actual image please?

**Comment by alvesjtiago** [comment]
@haizdesign implemented on the last release (https://github.com/alvesjtiago/hover-preview/releases/tag/0.0.15), it should update automatically. Let me know what you think 😊

**Comment by haizdesign** [comment]
Perfect! Thanks very much - this is really helpful.
