### ISSUE TITLE
[Feature request] Temporary images paths

### ISSUE THREAD

**Issue by Kristinita** [alvesjtiago/hover-preview#18]
### 1. Request

It would be nice, if [**`tmp_image.png`**](https://github.com/alvesjtiago/hover-preview/blob/master/hover_preview.py#L110-L112) files will be saved in [**temporary folder**](https://en.wikipedia.org/wiki/Temporary_folder), but not in projects folders.

### 2. Justification

Now `tmp_image.png` files saves in folders of my projects.

![tmp_image](http://i.imgur.com/AFeXHla.png)

I don't need these temporary images in folders of my projects, it unexpected for me.

Thanks.

**Comment by alvesjtiago** [comment]
@Kristinita you're right, these files should be stored elsewhere. Going to investigate that.

**Comment by alvesjtiago** [comment]
@Kristinita changed the temporary folder path on version 0.0.16 (https://github.com/alvesjtiago/hover-preview/releases/tag/0.0.16). Should update automatically. Thanks for reporting this.
