### ISSUE TITLE
support for absolute paths

### ISSUE THREAD

**Issue by AmjadHD** [alvesjtiago/hover-preview#20]
Would you consider adding support for absolute paths

**Comment by alvesjtiago** [comment]
Sure, could you provide an example? Thanks

**Comment by AmjadHD** [comment]
for example: C:\Users\User
\AppData\example.png.
That'll be perfect.

**Comment by AmjadHD** [comment]
The plugin already supports that :)

**Comment by AmjadHD** [comment]
#26
