### ISSUE TITLE
popup is too big

### ISSUE THREAD

**Issue by AmjadHD** [alvesjtiago/hover-preview#22]
The popup sometimes takes a lot of screen space, and i can't see the image's informations below

![popup_too_big](https://user-images.githubusercontent.com/33235928/35477571-fa3138c0-03c5-11e8-8bed-1e0a0a3eaa5f.gif)

**Comment by AmjadHD** [comment]
I think setting max_width and max_height to viewport_extent() won't solve the problem unless the popup is right in the center of the view
i made an attempt to fix that #21

**Comment by alvesjtiago** [comment]
Closing this. #21 and release https://github.com/alvesjtiago/hover-preview/releases/tag/0.0.17 implement these features.

Thank you so much @AmjadHD!
