### ISSUE TITLE
Support for srcset data-srcset and webp

### ISSUE THREAD

**Issue by Allmedialab** [alvesjtiago/hover-preview#23]
Hi,
First of all thanks for the nice and simple plugin!
Would it be possible to create support for the following code example?
Regards,
David

```<picture>
<div class="background-grid"></div>
                  <source media="(max-width: 475px) and (orientation: portrait)"
                  type="image/webp"
                  data-sizes="auto"
                  srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" 
                  data-srcset="
                  headers/header-stones-webp/stone-header-phone-600x400px.webp 600w,
                  headers/header-stones-webp/stone-header-phone-800x533px.webp 800w" class="lazyload">
                  <source media="(max-width: 475px) and (orientation: portrait)"
                  data-sizes="auto"
                  srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                  data-srcset="
                  headers/header-stones-jpg/stone-header-phone-600x400px.jpg 600w,
                  headers/header-stones-jpg/stone-header-phone-800x533px.jpg 800w" class="lazyload">
                  <source media="(max-width: 3500px)"
                  type="image/webp"
                  data-sizes="auto"
                  srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                  data-srcset="
                  headers/header-stones-webp/stone-header-800px.webp 800w,
                  headers/header-stones-webp/stone-header-1450px.webp 1450w,
                  headers/header-stones-webp/stone-header-2000px.webp 2000w,
                  headers/header-stones-webp/stone-header-2500px.webp 2500w" class="lazyload img-responsive">
                  <img
                  data-sizes="auto"
                  data-src="headers/header-stones-jpg/stone-header-800px.jpg"
                  srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                  data-srcset="
                  headers/header-stones-jpg/stone-header-800px.jpg 800w,
                  headers/header-stones-jpg/stone-header-1450px.jpg 1450w,
                  headers/header-stones-jpg/stone-header-2000px.jpg 2000w,
                  headers/header-stones-jpg/stone-header-2500px.jpg 2500w"
                  src="headers/header-stones-jpg/stone-header-800px.jpg" class="lazyload img-responsive"
                  alt="alt text">
                </picture>```

**Comment by alvesjtiago** [comment]
Hi @Allmedialab, thank you for the kind words 😊

Support for those data types was not on the priority list right now but I'll try to work on them in due time. If you want to open a PR that adds support it would be awesome.

Thanks

**Comment by AmjadHD** [comment]
I guess srcset = data urls, that is handled in #32 
remains the data-srcset and it shouldn't be difficult.

**Comment by alvesjtiago** [comment]
@Allmedialab version 0.0.22 implements changes made by @AmjadHD that allow the `srcset` part to be displayed. However there is still the `data-srcset` part to be implemented.

Hope it helps for now while the `data-srcset` is still in development.

**Comment by AmjadHD** [comment]
@alvesjtiago data url images are saved in the Temp directory as "myfile.\<extension\>"
https://github.com/alvesjtiago/hover-preview/blob/16a1c92201e681bf29a2938699380b581ceb7a25/hover_preview.py#L336

but when we want to save them, unlike url and path based images they have no real name, currently they are saved with their temp names ("myfile.\<extension\>"), that means if a data url image with the extension gif for example is saved we cannot save another with the same extension because they share the same name (myfile.gif).

**Comment by alvesjtiago** [comment]
@AmjadHD ideally we would generate a random name (eg. an UUID) on the save command for data-url images.

**Comment by AmjadHD** [comment]
i already tried to implement that but that means the same image can be saved twice.

**Comment by alvesjtiago** [comment]
Hashing the data-url content to a small string instead of a UUID would overcome that issue.

**Comment by AmjadHD** [comment]
how can we do that ?

**Comment by alvesjtiago** [comment]
I've just pushed an implementation for this @AmjadHD which will be released in the next version: https://github.com/alvesjtiago/hover-preview/commit/b1fa1f21754a869e0e84101e9f349ae7afb6529b

Take a look and let me know what you think. It's not guaranteed to be unique but it's also not critical.

**Comment by AmjadHD** [comment]
looks good :+1: , it's nice to learn something new :smile: , this hash stuff is certainly useful.

**Comment by AmjadHD** [comment]
#35

**Comment by alvesjtiago** [comment]
@AmjadHD the above snippet from @Allmedialab with `data-srcset` does not seem to be working on https://github.com/alvesjtiago/hover-preview/pull/35.

eg.

```
<source media="(max-width: 475px) and (orientation: portrait)" type="image/webp" data-sizes="auto" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="headers/header-stones-webp/stone-header-phone-600x400px.webp 600w, headers/header-stones-webp/stone-header-phone-800x533px.webp 800w" class="lazyload">
```

I'll try to check what might be the reason. With what example did you test?

Thanks again @AmjadHD.

**Comment by AmjadHD** [comment]
I tried it, it's working for me, but of course it doesn't show the images because i don't have the files

**Comment by alvesjtiago** [comment]
I had probably written the wrong path. Going to merge a release a new version. Thanks!
