### ISSUE TITLE
[Feature request] Preview by command

### ISSUE THREAD

**Issue by Kristinita** [alvesjtiago/hover-preview#24]
### 1. Summary

Sublime Text can hang 1—3 minutes, when I hover my cursor to image URL.

It would be nice, if you someday solve this problem.

### 2. Details

For example, I hover cursor to image URL in `![Sasha big image](https://i.imgur.com/scCrBeR.png)` Markdown link. I get result:

**WARNING: Big image below consume RAM**

**<https://i.imgur.com/LutXAww.png>**

I can accidentally hover my cursor to image URL → Sublime Text hangs. It takes a lot of time.

So I disable Hover Image Preview.

### 3. Possible solutions

It would be nice, if all be added, but if you add only one thing, it also not bad.

#### 3.1. Command mode

Expected behavior: I place my carriage to image link → I run command `hover_preview` use hotkey or command palette → image show for me in Sublime Text.

I.e., image show, if user run command, not if user hover cursor to image.

#### 3.2. Reduction of time

It would be nice, if images will be shown more quick, than now, that Sublime Text will hang less time.

#### 3.3. Configurable hover time

It would be nice, if would be possible set hover time.

For example,

if `hover_time: 3` in Hover Image Preview settings:

    user need hover cursor to image 3 seconds, not less, that image will be shown.

It can help, if user accidentally led the cursor through the image URL.

Thanks.

**Comment by alvesjtiago** [comment]
Thank you so much for the thorough description and possible solutions @Kristinita.

I'll try to investigate which option or options would be best. Making the image load on another thread (if possible) would reduce loading time and eliminate hanging time.

Once I get the chance I'll try to implement at least one solution.

Thanks

**Comment by AmjadHD** [comment]
#26 
downloading images is no longer blocking (it runs in a separate thread)
and it's a little faster cause the image was downloaded twice (with urlopen() then urlretrieve())

**Comment by AmjadHD** [comment]
can we close this ?

**Comment by alvesjtiago** [comment]
Yes @AmjadHD. Closing it now.

**Comment by AmjadHD** [comment]
#37 adds preview by command
