### ISSUE TITLE
[BUG]:popup is hidden when clicked

### ISSUE THREAD

**Issue by AmjadHD** [alvesjtiago/hover-preview#25]
When you click on the big popup outside the surface of the small popup it gets hidden !
apparently sublime text treats the big popup as the small one.

**Comment by AmjadHD** [comment]
i couldn't provide a gif, but you can test it, just open a big image then click on the popup outside of where the small popup would appear.

**Comment by alvesjtiago** [comment]
Works for me but only if I do not move the mouse afterwards. Not sure if there is a way to overcome this.

**Comment by AmjadHD** [comment]
Maybe show_popup instead of update_popup will solve it.
