### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Alexisgarci** [alvesjtiago/hover-preview#30]
Hi guys, im on mac os mojave and i cant put this to work. ive installed it thru the package controll and then ive installed it manualy, it wont work and it even wont show up in the Sublime Text -> Preferences -> package settins. Any tips so i can make this work? tnks

**Comment by alvesjtiago** [comment]
Hi @Alexisgarci, I still haven't tested it on mojave but I'll let you know as soon as I do. Did it work before you updated to mojave? Can you tell me if there's any error thrown when you hover over an image on the Sublime Text console? Thank you

**Comment by Alexisgarci** [comment]
Ive never tried it before, so i dont know if it was working before mojave, and i see no errors in console.
![screenshot 2018-12-18 at 17 32 24](https://user-images.githubusercontent.com/35870834/50171670-f656d780-02ea-11e9-9d34-cab816337a3f.png)

**Comment by alvesjtiago** [comment]
From your screenshot it looks like you're trying to preview images from relative paths. This will only work if you have the whole project open on Sublime Text (i.e. the folder of the project). Can you please try? Thank you

**Comment by alvesjtiago** [comment]
Hi again @Alexisgarci, were you able to test this again by opening the whole project? Closing this for now but let me know if you still can't use hover-preview.
