### ISSUE TITLE
Modify version numbers

### ISSUE THREAD

**Issue by AmjadHD** [alvesjtiago/hover-preview#34]
The current versioning system doesn't seem intuitive, can we instead use the one that goes like 0.0.1 to 0.0.9 then 0.1.0, 0.1.1 etc, it is used in all the softwares I know and it reflects more the progress made in this plugin.

**Comment by alvesjtiago** [comment]
@AmjadHD hover-preview is using Semantic Versioning (https://semver.org/). But I will transition to 0.1.0 in the next release. Thanks
