### ISSUE TITLE
Consider changing name to Image Preview

### ISSUE THREAD

**Issue by alvesjtiago** [alvesjtiago/hover-preview#39]
As suggested by @AmjadHD, we should consider changing the name of the plugin to Image Preview since it now works without hovering.

**Comment by AmjadHD** [comment]
I made the new entry in https://github.com/wbond/package_control_channel, I also made some modifications:
- added description and labels
- modified the minimum version of sublime to >= 3124 since earlier versions don't have hover API
- changed the repo url, supposing you're gonna rename the repo as well

```json
		{
			"name": "Image Preview",
                        "previous_names": ["Hover Image Preview"],
                        "description": "The Sublime Text image previewing plugin",
                        "labels": ["image", "preview"],
			"details": "https://github.com/alvesjtiago/sublime-image-preview",
			"releases": [
				{
					"sublime_text": ">=3124",
					"tags": true
				}
			]
		},
```

**Comment by AmjadHD** [comment]
can you also add more tags to the repo, like <kbd>image-preview</kbd>.

**Comment by alvesjtiago** [comment]
Thanks @AmjadHD. Yes we should probably rename to `Image Preview` and add a couple more labels.

**Comment by AmjadHD** [comment]
@alvesjtiago, after checking the [naming guidelines](https://packagecontrol.io/docs/submitting_a_package#Step_2), I believe the new name should be "ImagePreview" (attached)
so the package entry would become:
```json

		{
			"name": "ImagePreview",
                        "previous_names": ["Hover Image Preview"],
                        "description": "The Sublime Text image previewing plugin",
                        "labels": ["image", "preview"],
			"details": "https://github.com/alvesjtiago/sublime-image-preview",
			"releases": [
				{
					"sublime_text": ">=3124",
					"tags": true
				}
			]
		},
```
I already made the required changes in c1b0efb423317ad1e28fe87505d0f3ea050c1409

**Comment by AmjadHD** [comment]
Also maybe add `file` and `url` labels, so the package entry becomes:
```json
		{
			"name": "ImagePreview",
                        "previous_names": ["Hover Image Preview"],
                        "description": "The Sublime Text image previewing plugin",
                        "labels": ["image", "preview", "file", "url"],
			"details": "https://github.com/alvesjtiago/sublime-image-preview",
			"releases": [
				{
					"sublime_text": ">=3124",
					"tags": true
				}
			]
		},
```
