### ISSUE TITLE
issue with long lines and the "max_chars" setting

### ISSUE THREAD

**Issue by AmjadHD** [alvesjtiago/hover-preview#40]
like discussed in https://github.com/alvesjtiago/hover-preview/issues/29#issuecomment-466727143 and after, long data urls are trimmed to respect the "max_chars" setting thus the data is incomplete and the image is not previewed.

**Comment by alvesjtiago** [comment]
@AmjadHD is this issue fixed with the latest merges? Thanks!

**Comment by AmjadHD** [comment]
Yes, this was just opened for the record.

**Comment by alvesjtiago** [comment]
Great! Closing now.
