### ISSUE TITLE
Wrong path after update

### ISSUE THREAD

**Issue by Allmedialab** [alvesjtiago/hover-preview#41]
Hi,
A link like this doesn't work: assets/images/black-and-white.jpg 
A link like this works: ../assets/images/black-and-white.jpg
The top one is the proper path and the bottom one is the wrong path!
Regards & Thanks,
David

**Comment by AmjadHD** [comment]
- are there project folders open in the window ?
- what's the position of the file in which the links are referenced relative to the position of the image (a simple directory tree representation or screenshot would be welcomed) ?
- have you changed the  "search_mode"and "recursive" settings ?

**Comment by Allmedialab** [comment]
Hi,
No it all changed after the last update. Projects that used to work don't work anymore. Never changed anything in the preferences. Only when I add ../ to a path it works, but then my images don't show, because it's the wrong path.
The path is for example: src="Responsive-Images/galerie/header-galerie/jpg/header-galerie-1000-250.jpg" class="lazyload img-responsive"
And when I change it in: src="../Responsive-Images/galerie/header-galerie/jpg/header-galerie-1000-250.jpg" class="lazyload img-responsive" it works, but my images don't show it's the wrong path.

**Comment by AmjadHD** [comment]
> Only when I add ../ to a path it works, but then my images don't show

* can you clarify more what do you mean by "it works" ?
* can you provide the path to the file where the image path is referenced ?
thanks.

**Comment by Allmedialab** [comment]
I mean when I add ../ to a path the plugin works, but then I have the wrong path for my website.
Don't understand your second question. The path is:
src="Responsive-Images/galerie/header-galerie/jpg/header-galerie-1000-250.jpg" 
In reality there is one project folder holding the above link that's it.

**Comment by AmjadHD** [comment]
I mean what's the name of the file where this sentence
`src="Responsive-Images/galerie/header-galerie/jpg/header-galerie-1000-250.jpg"` is written ?
(e.g index.html)
now is this file located in the project ? where exactly (the filepath) ?
where is "Responsive-Images" located ? in the root of the project ?
I need these informations to try to reproduce the issue.

**Comment by Allmedialab** [comment]
OK I see what you mean:
ProjectFolder/header-images/Friture/header-friture-jpg/header-friture-1000px-250px.jpg
ProjectFolder/index.php

**Comment by Allmedialab** [comment]
Can you reproduce the issue?

**Comment by Cooperdale** [comment]
Hello, I have the same issue, paths not working after a recent update. I can't see previews anymore on most of my projects.

**Comment by Costegillio** [comment]
Same problem:
1. Doesn't work: 'hub/vibro.jpg'.
2. Works: 'https://www.google.com/logos/doodles/2019/first-day-of-school-2019-september-1-4646309670682624-law.gif'

Nothing was changed in settings.

Hierarchy of files:
hub/ <- dir with 'vibro.jpg'.
index.html <- file with img.

**Comment by AmjadHD** [comment]
@Allmedialab, @Cooperdale, @Costegillio, I'm sorry for the late response, this will be fixed in a6a1a07580dd624fd3fc16bc8f1b21cf281e8049. creating a regex that handles all kinds of paths and uris seems more difficult than I thought.

**Comment by Cooperdale** [comment]
> @Allmedialab, @Cooperdale, @Costegillio, I'm sorry for the late response, this will be fixed in [a6a1a07](https://github.com/alvesjtiago/hover-preview/commit/a6a1a07580dd624fd3fc16bc8f1b21cf281e8049). creating a regex that handles all kinds of paths and uris seems more difficult than I thought.

Regex is always more difficult than anyone thinks it will be.

**Comment by alvesjtiago** [comment]
Sorry about the delay reviewing the changes. I'm going to prepare the name change and look to submit an updated version tomorrow. Thank you @AmjadHD for fixing this issue and @Allmedialab from bringing it up.

**Comment by Allmedialab** [comment]
The issue still remains in Windows and Mac!


`<img src="assets/images/rest-header-hi-res.jpg" class="img-fluid"> `  
doesn't work.


Have to change the path in:
`<img src="../assets/images/rest-header-hi-res.jpg" class="img-fluid">` 
works but is the wrong path

**Comment by AmjadHD** [comment]
@Allmedialab, Are you using the master branch of https://github.com/AmjadHD/hover-preview ?

**Comment by Allmedialab** [comment]
@AmjadHD  No I'm using the version available in the Package Manager of Sublime 3, because I received a mail concerning the coming update a couple of weeks ago.

**Comment by AmjadHD** [comment]
The PR was not merged yet, ping @alvesjtiago to speed things up a little 😊

**Comment by Allmedialab** [comment]
OK and is it fixed now?👍😊

**Comment by AmjadHD** [comment]
Yes 👌
