### ISSUE TITLE
Use full image url to preview image file when using server-side editing

### ISSUE THREAD

**Issue by gkenBH** [alvesjtiago/hover-preview#44]
Hi, We use imgIX to modify our images server-side so our urls look something similar to this:
[https://s3-brentwoodhome.imgix.net/sale/winterhero.jpg?rect=376,0,1365,1365&bri=-8&txtalign=middle,center&txtfont=Didot,Italic&txt=Veteran's%20Day%20Sale&txtclr=FFFFFF&txtsize=42&w=414](url)

At present, hover-preview can only preview "https://s3-brentwoodhome.imgix.net/sale/winterhero.jpg" so it's only displaying the original image, ignoring all the parameters. Is it possible to have the option of looking at the entire url instead of just stopping at the file name? It would be very useful. The Brackets code editor does this really well if you want to check it out but I'd like to use Sublime instead.

**Comment by alvesjtiago** [comment]
Hi @gkenBH, version [0.2.2](https://github.com/alvesjtiago/hover-preview/releases/tag/0.2.2) should fix this issue. I've just released this version and as soon as it's captured by [package control](https://packagecontrol.io/packages/ImagePreview) it should update automatically on your end 😊

I will close the issue meanwhile but feel free to report back if it's working or not so I can investigate further. Thank you!

**Comment by gkenBH** [comment]
Thank you so so much, it's working! :)
