### ISSUE TITLE
Image Preview is not working for MacOSx Lion

### ISSUE THREAD

**Issue by atantos** [alvesjtiago/hover-preview#45]
Hi there! 

Thanks a lot for the wonderful plugin! Have been using it for a while and works perfectly. However, these last couple of days I cannot preview any image files with local paths from within a markdown or any other type of file when I hover over a path; although I can preview images with web urls. I did not change anything from the package settings file and I also do not seem to be able to open any image even with the right-click "Image Preview" option. 

I saw that you applied some changes these last days. Do you think you could look at it again? 

Thanks!

Alex

**Comment by alvesjtiago** [comment]
Thank you so much for the kind words @atantos. Can you give me an example to reproduce locally and fix it as soon as possible? Thank you

**Comment by atantos** [comment]
Thanks for the prompt reply!

Am not sure how to reproduce this type of problem, since there is no error shown..nothing really happens. 

However, within an md file I have the following passage:
---
![](/Users/Alexandros/Documents/Multivariate/Snapshots/Various/19.30.14.png)

*Step 10*: Refine model (refine the predictors) and check model fit
This is the stage of model building. 
---
here is the link to the file if you would like to use it: 

![13 59 54](https://user-images.githubusercontent.com/9120855/72881041-b261ad80-3d08-11ea-8105-401f04909f8c.png)

The link is correct but the image does not popup any more..I also tried with many other snapshot images and the same applies to them. The strange thing is that web links do work!

Do you think you could help me with the info you need? Am really sorry if these directions are not particularly helpful. Am not a sublime text expert unfortunately am not aware of what you would need in this case. 

Looking forward to hearing what you need in order to be more helpful.

Alex

**Comment by atantos** [comment]
The local path does not show up in my previous message:

/Users/Alexandros/Documents/Multivariate/Snapshots/Various/19.30.14.png

Just in case there is anything to do with the path..although it used to work perfectly before.

**Comment by alvesjtiago** [comment]
Thanks @atantos! I'm going to try and take a look later today to reproduce it and I'll let you know what I can find.

**Comment by alvesjtiago** [comment]
Hi again @atantos, version [0.2.1](https://github.com/alvesjtiago/hover-preview/releases/tag/0.2.1) should fix this issue. As soon as [package control](https://packagecontrol.io/packages/ImagePreview) refreshes to the new version you should receive an automatic update 😊 
I will close the issue meanwhile but please feel free to let me know if it's fixed and if not if you get any error. Thank you for your report and hope that this change makes your life easier!
