### ISSUE TITLE
[Bug] Package not working in Windows 64-bit

### ISSUE THREAD

**Issue by Kristinita** [alvesjtiago/hover-preview#5]
### 1. Summary

Hover Preview not worked for me.

### 2. Expected behavior

![Expected](https://camo.githubusercontent.com/03d27899f3133b0283790db066b0afbf7c842e44/687474703a2f2f692e696d6775722e636f6d2f634e74384b76352e6a7067)

### 3. Actual behavior

Not image preview.

### 4. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

For example, I have `test.html` file:

```html
<img src="anima_images/Kiravel.jpg">
<img src="https://packagecontrol.io/readmes/img/dfafcd2b8d9e12e61495cc1f7024cde90117f457.jpg">
```

Paths is correct both. I install Hover Preview via Package Control → I restart Sublime Text → I hover my cursor to `anima_images/Kiravel.jpg` and `https://packagecontrol.io/readmes/img/dfafcd2b8d9e12e61495cc1f7024cde90117f457.jpg` → I wait 30 seconds → images don't shown for me.

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126

Thanks.

**Comment by alvesjtiago** [comment]
Hi @Kristinita, thank you for the thorough report about the issue.

Right now, hover-preview only displays images inside the opened project on Sublime Text so if you only have `test.html` in Sublime it won't search outside of the folder structure that you have opened. I decided to keep it this way in order to avoid unnecessary search outside of the current working directory and maximize performance. Would you mind opening the project folder that you're working on that includes both `test.html` and the image and let me know if it works?

Regarding the html link pointing to an image, it would be great to show a preview of the image by loading it directly from the link. I'll open this feature as a separate ticket and mention this one.

Once again, thank you for your feedback.

**Comment by Kristinita** [comment]
@alvesjtiago , my `test.html` file is situated in my project folder in sidebar. `anima_images/Kiravel.jpg` also in my project. I think, it would be nice, if I can see preview my `anima_images/Kiravel.jpg` file.

Thanks.

**Comment by alvesjtiago** [comment]
You are right @Kristinita, I was testing with several jpg images and while some indeed work, others didn't. It was an issue with the code calculating the size of the image but which does not seem to be necessary to render it. Therefore I've removed it and now every image seems to be rendering correctly. 

Please install version 0.0.3 and let me know if your `anima_images/Kiravel.jpg` image works.

Thanks

**Comment by Kristinita** [comment]
@alvesjtiago , if you add more descriptions and examples of Usage for your packages, more users will be use it.

Also, I don't understand, how works [**Click To Partial**](https://github.com/alvesjtiago/click-to-partial) package.

Thanks.

**Comment by alvesjtiago** [comment]
Thanks @Kristinita, I will. What do you suggest for [Hover Preview](https://github.com/alvesjtiago/hover-preview)? More images exemplifying its usage? A better description of when and how it's working right now and future developments?

Regarding [Click To Partial](https://github.com/alvesjtiago/click-to-partial), it is only for Ruby on Rails development. It opens a partial file if you cmd+shift+click on its reference on another file. I will also add a better description and a gif illustrating it.

**Comment by Kristinita** [comment]
@alvesjtiago , far plugin still didn't work for me in 0.0.3 version.

I hover my cursor to relative paths for `.jpg` and `.png` in my `test.html` file → I wait 30 seconds → nothing occurs.

Additional troubleshooting information:

<details>
<summary>
<b>Click here to see full log.</b></summary><br>

```
### Editor info (as provided by Sublime Text API)

*General details about Sublime Text*

##### Version and architecture

> **name:** Sublime Text  
> **version:** 3126  
> **architecture:** x64  
> **channel:** stable  
> **platform:** windows  

##### Package data

> **installed packages:** ["0_package_control_loader", "Hover Image Preview", "Logging Control", "memTask", "Package Control", "PackageResourceViewer", "SashaSublime", "Schemr", "Troubleshooting"]  
> **packages:** ["markupsafe", "Mediawiker", "memTask", "oauthlib", "python-jinja2", "python-pywin32", "requests", "requests-oauthlib", "Theme - Default", "User"]  
> **ignored packages:** ["Mediawiker", "memTask", "Schemr", "Vintage"]  
> **packages managed by Package Control:** ["Hover Image Preview", "Logging Control", "Mediawiker", "memTask", "Package Control", "PackageResourceViewer", "SashaSublime", "Schemr", "Troubleshooting"]  

##### View settings

> **syntax:** Packages/Markdown/Markdown.tmLanguage  
> **tab_size:** 4  
> **translate_tabs_to_spaces:** False  
> **encoding:** Undefined  
> **em width:** 10.99609375  
> **selection count:** 1  
> **has non empty selections:** False  

##### View state

> **is view dirty:** True  
> **is view readonly:** False  

##### Profiling data (as reported by Default/profile.py)

```
on_activated:
    Default.pane: 0.000s total, mean: 0.000s, max: 0.000s

on_deactivated:
    Default.history_list: 0.000s total, mean: 0.000s, max: 0.000s

on_modified:
    Default.settings: 0.001s total, mean: 0.000s, max: 0.001s
    PackageResourceViewer.package_resource_viewer: 0.000s total, mean: 0.000s, max: 0.000s
```

### Platform info (as provided by wmic.exe)

*Details about the current platform*

##### Display information

> **OSArchitecture:** 64-bit  
> **Version:** 10.0.14393  
> **BuildNumber:** 14393  
> **BuildType:** Multiprocessor Free  
> **Caption:** Microsoft Windows 10 Enterprise 2016 LTSB  
> **FreePhysicalMemory:** 1786052  
> **FreeSpaceInPagingFiles:** 4170172  
> **FreeVirtualMemory:** 5501216  

##### Display information

> **PixelsPerXLogicalInch:** 96  
> **PixelsPerYLogicalInch:** 96  

---
This report was generated by the [Troubleshooting][self] package.

[self]: https://github.com/guillermooo/sublime-troubleshooting
```
</details><br>

Thanks.

**Comment by Kristinita** [comment]
> Thanks @Kristinita, I will. What do you suggest for Hover Preview? More images exemplifying its usage? A better description of when and how it's working right now and future developments?

I'm sure the more you add, your plugin will be more popular. You can also announce your plugin on the [**forum**](https://forum.sublimetext.com/) that it knew more users.

Thanks.

**Comment by alvesjtiago** [comment]
@Kristinita I've set up a VM with Windows 10, installed ST3 and the plugin and everything seems to be working fine. Here's a screenshot:

<img width="1009" alt="screen shot 2017-01-22 at 19 35 23" src="https://cloud.githubusercontent.com/assets/407470/22184889/311bcfb2-e0db-11e6-8a27-cab66e12d306.png">

Can you please show me the code you're trying to use and the image?

Thanks

**Comment by alvesjtiago** [comment]
@Kristinita were you using this file structure? Did you manage to get it to work?

**Comment by Kristinita** [comment]
@alvesjtiago, [**my 4 images**](https://github.com/Kristinita/Kristinita.github.io/blob/master/hover-preview.html#L10-L13):

1. For links, I see scrollbars. It would be nice, if users will be see full image without scrollbars.

![Scrollbars](http://i.imgur.com/J1EOtlM.png)

2. I don't see images for relative paths.
3. Cyrillic symbols in URL [**don't support**](https://github.com/alvesjtiago/hover-preview/blob/master/hover_preview.py#L60).
4. `jpeg`, `bmp` extensions [**don't support**](https://github.com/alvesjtiago/hover-preview/blob/master/hover_preview.py#L67).

Thanks.

**Comment by alvesjtiago** [comment]
@Kristinita 

1. Unfortunately the Sublime API for previews, as far as I know, does not allow the size to be manually adjusted to more than what you see on your image. If this changes, I'll upgrade accordingly.
2. Could you provide a screenshot of your side bar with the current open files.
3. I'll add a separate ticket for this.
4. Just added support on the latest version 0.0.5

Thank you

**Comment by Kristinita** [comment]
@alvesjtiago,

1. In Mediawiker package [**image size is larger**](https://github.com/tosher/Mediawiker/issues/110). But also with scrollbars :crying_cat_face: . Maybe will be better to create feature request in [**Sublime Text Core**](https://github.com/SublimeTextIssues/Core/issues)?

2. ![Sidebar](http://i.imgur.com/lxW21FM.png)  
Half of folders of my sidebar is not local git repositories. And I don't think, that sidebar dependency is a good idea.

3. For Cyrillic symbols we can use `[0-9A-ZA-ЯЁ]`, but other languages still will not be supported. Maybe better use [**regular expressions for links**](https://mathiasbynens.be/demo/url-regex) or [**don't use regular expressions**](http://stackoverflow.com/a/1732454/5951529)?

4. Now it worked for me. Thanks!

**Comment by alvesjtiago** [comment]
@Kristinita 

1. I think it's worth creating a feature request for resizing the popup container.
2. I changed the base folder path search, it should work now on version 0.0.6. Can you please update and test?
3. Also introduced a change on the IRI to URL encoding. It should be working find now. Please update to 0.0.6.
4. Great 😊

This last version 0.0.6 should address all the issues you were having.
Thanks for reporting everything.

**Comment by Kristinita** [comment]
@alvesjtiago , preview don't working, if I hover my mouse to `Шоколадка.jpg` [**here**](https://github.com/Kristinita/Kristinita.github.io/blob/master/Sublime-Text/SashaSublime.html#L86):

Thanks.

**Comment by alvesjtiago** [comment]
@Kristinita do you have that file opened on the sidebar of Sublime Text? I just tested with a file with the same name and it's working fine.

<img width="841" alt="screen shot 2017-02-03 at 17 15 08" src="https://cloud.githubusercontent.com/assets/407470/22600866/611a97ae-ea34-11e6-997e-9439cd598d78.png">

**Comment by Kristinita** [comment]
No, I didn't have my folder in sidebar. When I add my folder in sidebar, 
Hover Preview worked for me :-).

Please, add information about sidebar in README.MD.

Thanks.

**Comment by alvesjtiago** [comment]
@Kristinita added! 😊
Once again thanks for all the feedback.

**Comment by Kristinita** [comment]
@alvesjtiago , thank you! We wait, what will you do with popup container size.
