### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by Cooperdale** [alvesjtiago/hover-preview#9]
Hello, this plugin is great. It would be perfect if, instead of loading the full image, it showed a thumbnail of the image, with a fixed width maybe. Sometimes the full image is too big and you can only see a small part of it, which makes it less useful.

Thanks.

**Comment by alvesjtiago** [comment]
That's a great suggestion @Cooperdale! I'm going to check how to implement it despite the current constraints from ST3. Thanks

**Comment by Cooperdale** [comment]
Not my idea actually. I copied it from Dreamweaver :). 
![image](https://cloud.githubusercontent.com/assets/2644219/22932477/5ad106de-f2c8-11e6-8944-d2980d98f79b.png)

**Comment by alvesjtiago** [comment]
@Cooperdale nevertheless useful 🙂
I've just released a new version 0.0.8 that adjusts the size of local images to the popup size. It should update automatically on your end. Let me know what you think. 
I'd still have to implement a similar flow for remote images.

@Kristinita until a larger popup is available through ST3 API, what do you think about this?

**Comment by Cooperdale** [comment]
It works great! Thanks, you are The Man!

**Comment by alvesjtiago** [comment]
Glad you liked it @Cooperdale 🙂 thanks for the suggestion

**Comment by Kristinita** [comment]
@alvesjtiago , thanks! It would be nice, if images will be more larger.

![Шоколадка](http://i.imgur.com/tfl6Ven.png)

And we wait this feature for remote images.

**Comment by Kristinita** [comment]
@alvesjtiago , any ideas, how show remote images without scrollbars like local images?

Thanks.

**Comment by alvesjtiago** [comment]
@Kristinita yeah, I'd have to download the image first and calculate the dimensions prior to displaying them. Going to reopen this ticket to work on the same functionality for remote images.

**Comment by Kristinita** [comment]
@alvesjtiago , status?

Thanks.

**Comment by alvesjtiago** [comment]
Hi @Kristinita, I still didn't have a chance to work on this feature but I hope I can do it in the next couple of days. I'll keep you posted. Thanks

**Comment by alvesjtiago** [comment]
@Kristinita this last release should add the ability to see remote images fitting to the size of the popup window. Let me know what you think.

**Comment by Kristinita** [comment]
@alvesjtiago, thanks, it works for me!

![**Itog**](http://i.imgur.com/7aiZnCC.png)

And I think, it would be nice, if would be possible make image size larger. As you can see, the details on image are not very visible.

Thanks.

**Comment by alvesjtiago** [comment]
@Kristinita great! The image size unfortunately can't be larger due to the window popup dimension restrictions of Sublime Text 3 without displaying sliders so I will close this issue. Thank you for your feedback!

**Comment by Kristinita** [comment]
> The image size unfortunately can't be larger due to the window popup

@alvesjtiago, maybe it would be nice to create an issue in [**Sublime Text Core**](https://github.com/SublimeTextIssues/Core/issues)?

Thanks.

**Comment by alvesjtiago** [comment]
@Kristinita yes, I will do that 😊
